name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REACT_APP_BACKEND_BASE_URL: https://chat-app-arvid.herokuapp.com/
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        
      - name: install and build
        run: |
          yarn install --frozen-lockfile
          yarn build
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: build
